service: acheev-backend

# Use the serverless-webpack plugin to transpile ES6
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-s3-sync

package:
  individually: true
  exclude:
    - test/**
    - .git/**

# serverless-webpack configuration
# Enable auto-packing of external modules
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  cfLogs: true
  stage: ${opt:stage, 'dev'}
  environment: ${file(env.yml):${self:provider.stage}}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::${self:provider.environment.ACHEEV_BUCKET}/*"

functions:
  account:
    handler: handler.account
    events:
      - http:
          path: account
          method: ANY
          cors: true
      - http:
          path: account/{proxy+}
          method: ANY
          cors: true

  auth:
    handler: handler.auth
    events:
      - http:
          path: auth
          method: ANY
          cors: true
      - http:
          path: auth/{proxy+}
          method: ANY
          cors: true

  invite:
    handler: handler.invite
    events:
      - http:
          path: invite
          method: ANY
          cors: true
      - http:
          path: invite/{proxy+}
          method: ANY
          cors: true

  offer:
    handler: handler.offer
    events:
      - http:
          path: offer
          method: ANY
          cors: true
      - http:
          path: offer/{proxy+}
          method: ANY
          cors: true

  rating:
    handler: handler.rating
    events:
      - http:
          path: rating
          method: ANY
          cors: true
      - http:
          path: rating/{proxy+}
          method: ANY
          cors: true

  subscription:
    handler: handler.subscription
    events:
      - http:
          path: subscription
          method: ANY
          cors: true
      - http:
          path: subscription/{proxy+}
          method: ANY
          cors: true

  transaction:
    handler: handler.transaction
    events:
      - http:
          path: transaction
          method: ANY
          cors: true
      - http:
          path: transaction/{proxy+}
          method: ANY
          cors: true

  user:
    handler: handler.user
    events:
      - http:
          path: user
          method: ANY
          cors: true
      - http:
          path: user/{proxy+}
          method: ANY
          cors: true
